"""Add stripe_session_id to tickets

Revision ID: 873bdd0770cc
Revises: 911351664513
Create Date: 2025-12-01 11:14:33.426827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873bdd0770cc'
down_revision: Union[str, None] = '911351664513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ticket_price', sa.Float(), nullable=False, server_default="0"))
    op.add_column('tickets', sa.Column('stripe_session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tickets_stripe_session_id'), 'tickets', ['stripe_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_stripe_session_id'), table_name='tickets')
    op.drop_column('tickets', 'stripe_session_id')
    op.drop_column('events', 'ticket_price')
    # ### end Alembic commands ###
